INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('title1', 'category1', 1, '1-1-2020', '4-1-2020');

INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);
INSERT INTO users (name, age) VALUES ('name1', 30);

INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 1, 1);